### ISSUE TITLE
Solved: Multiple server forward just like client?

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [twisteroidambassador/ptadapter#4]
This is the "standalone_client_config.ini".
```
[transports]
# Define transports supported by the PT here. Each supported transport type may
# have several clients with different options. Syntax:
# <config-section> = <transport-name>
# config-section is case-insensitive, and must not be "common" or "default".
obfs4-client1 = obfs4
obfs4-client2 = obfs4
obfs4-client3 = obfs4
```

We can use single client process manage three-more client instance.
And is there any possible to forward so much more address and port by single server process?
("standalone_server_config.ini")

**Comment by twisteroidambassador** [comment]
A pluggable transport may support forwarding different protocols in a single process. For example, obfs4proxy can forward obfs2, obfs3, obfs4 (each listening on a different port, all forward to the same port) at the same time.

However, a single pluggable transport process can not listen on multiple ports with the same protocol. (I *think* I tried making obfs4proxy listen for obfs4 on two ports back in the days, and while both ports appear to be listening, only one actually worked.) 

So, in order to listen for the same protocol on multiple ports, multiple pluggable transport processes must be run, and the script does not currently support that. For now, just run multiple copies of this script with different config files and state directories.

**Comment by mhtvsSFrpHdE** [comment]
@twisteroidambassador Understood. And thank you.
