### ISSUE TITLE
standalone.py

### ISSUE THREAD

**Issue by awoolford** [twisteroidambassador/ptadapter#6]
I am following instructions on installing obfs4proxy with openvpn here:  https://mosin.ca/index.php/2018/09/05/setting-up-openvpn-with-obfs4proxy/

The startup script includes:
ExecStart=/usr/bin/python3 /etc/openvpn/pluggabletransportadapter/standalone.py --server /etc/openvpn/pluggabletransportadapter/standalone_server_config.ini

However, the git clone directory does not include the scripts 'standalone.py' or 'standalone_server_config.ini'.  I have created the server ini file from the example_config.ini, but am stuck without the standalone.py file.

I am also using a redhat fork (like centos) which has python 3.6 installed.  The original howto called for python3.  Will 3.6 work the same?

I am assuming the files have changed since the howto was published.  Can you please advise the current procedure?

**Comment by twisteroidambassador** [comment]
Yes, the code has changed significantly in the meantime. The current code requires Python 3.7 or up. To use the latest version, you can check out the documentation, linked from the front page of the repository and in README.md.

However, since you only have Python 3.6, the easiest thing to do is to download an older release that match the guide you're using: https://github.com/twisteroidambassador/ptadapter/releases/tag/v1.9.1-alpha

**Comment by awoolford** [comment]
Many thanks for the link.

I am no expert and as the Readme for the latest version does not reference the specific example in the guide, (obviously), I was rather lost.  I’m not sure if Python 3.7 is even available for this distro I am using (sangoma freepbx - based on centos).

So the link to the earlier version will be very helpful indeed.

Kind regards.

Andy
